name: Remove from AWS

permissions: {}

on:
  workflow_dispatch: # Trigger manually

env:
  TF_VERSION: "1.10.4"
  AWS_REGION: "eu-central-1"

jobs:
  deploy:
    name: Deploy to AWS using Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@1bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS OIDC credentials
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_BUCKET_PATH }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TFSTATE_TABLE_NAME }}"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve  \
            -var="my_own_public_ip=${{ secrets.MY_PUBLIC_IP }}"