name: 'Validate and deploy to AWS'

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main


env:
  TF_VERSION: "1.10.4"
  AWS_REGION: "eu-central-1"

jobs:
  validate:
    name: Validate Terraform code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Check Terraform Formatting
        id: fmt-check
        run: terraform fmt -check -recursive
    
      - name: Fail if Format Changes Are Needed
        if: ${{ failure() }}
        run: |
          echo "::error::Terraform formatting issues found. Please run 'terraform fmt' locally and commit the changes."
          exit 1

  deploy:
    name: Deploy to AWS using Terraform
    runs-on: ubuntu-latest

    needs:
      validate

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS OIDC credentials
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_BUCKET_PATH }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TFSTATE_TABLE_NAME }}"

      - name: Terraform Plan
        run: |
          terraform plan  \
            -var="my_own_public_ip=${{ secrets.MY_PUBLIC_IP }}" \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply tfplan